### ISSUE TITLE
can't import package

### ISSUE THREAD

**Issue by setnone** [mighdoll/undo-peasy#1]
i'm trying to add undo-peasy to my project and i'm getting this error

```
import { createStore } from 'easy-peasy';
import { undoRedo } from 'undo-peasy';
import storeModel from '../model';

const store = createStore(storeModel, { middleware: [undoRedo()] });

export default store;

```

> Failed to compile.
./node_modules/undo-peasy/src/Api.ts 12:7
Module parse failed: Unexpected token (12:7)
You may need an appropriate loader to handle this file type.
| export { undoRedo, undoable, useUndoGroup };
| 
> export type { WithUndo, ActionStateFilter, KeyPathFilter };
|

**Comment by mighdoll** [comment]
Ah. It looks like I've not published it correctly for people w/o typescript. I will take a look.

**Comment by setnone** [comment]
Thank you for the package and the update!
I'm having no issues so far.
